apiVersion: apps/v1
kind: Deployment
metadata:
    name: devops-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: swiggy
    template:
        metadata:
            labels:
                app: swiggy
        spec:
        containers:
            - name: appcont
              image: ananyapinninti/project:k8sdockerapp-AppImg
              ports:
                - containerPort: 8080
              imagePullSecrets
                - name:
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: devops-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: swiggy
    template:
        metadata:
            labels:
                app: swiggy
        spec:
        containers:
            - name: appcont
              image: ananyapinninti/project:k8sdockerapp-AppImg
              ports:
                - containerPort: 8080
              imagePullSecrets
                - name:
