apiVersion: apps/v1
kind: Deployment
metadata:
    name: deploy-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: swiggy
    template:
        metadata:
            labels:
                app: swiggy
        spec:
        containers:
            - name: appcont
              image: ananyapinninti/project:k8sdockerapp-AppImg
              ports:
                - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
        name: app-svc
spec:
        type: LoadBalancer
        selector:
                app: swiggy
        ports:
                - port: 8080
                  targetPort: 8080
