apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: db-deploy
spec:
    replicas: 1
    selector:
        matchLabels:
            app: zomato
    template:
        metadata:
            labels:
                app: zomato
        spec:
            containers:
                - name: db-cont
                  image: ananyapinninti/project:k8sdockerapp-DBImg
                  ports:
                    - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
        name: db-svc
spec:
        clusterIP: None
        selector:
                app: zomato
        ports:
                - port: 3306
                  targetPort: 3306
